export const copy = {
  reservar: 'Reservar turno',
  reservarDesc: 'Elegí servicios, profesional y horario en pocos pasos.',
  volverInicio: 'Volver al inicio',
  continuar: 'Continuar',
  volver: 'Volver',
  confirmar: 'Confirmar reserva',
  servicios: 'Servicios',
  profesional: 'Profesional',
  fechaHora: 'Fecha y hora',
  tusDatos: 'Tus datos',
  resumen: 'Resumen',
  cualquiera: 'Cualquier disponible',
  sinHorarios: 'No hay horarios este día. Probá con otra fecha.',
  slotOcupado: 'Ese horario ya no está disponible. Elegí otro.',
  reservasPausadas: 'Las reservas están pausadas por el momento.',
  mantenimiento: 'Estamos en mantenimiento. Volvé a intentar más tarde.',
  bloqueada: 'Esta página no está disponible.',
  pagoOnlineProximamente: 'El pago online no está configurado. Contactá al local para reservar.',
  pagoProcesando: 'Estamos procesando tu pago...',
  pagoExitoRedirigiendo: 'Pago recibido. Confirmando tu turno...',
  pagoError: 'No pudimos procesar el pago.',
  pagoReintentar: 'Reintentar pago',
  pagoPendiente: 'Tu pago está pendiente de confirmación.',
  politicaCancelacion: 'Acepto la política de cancelación del local.',
  agregarCalendario: 'Agregar al calendario',
  gestionarTurno: 'Gestionar mi turno',
  cancelarTurno: 'Cancelar turno',
  reprogramarTurno: 'Reprogramar turno',
  turnoConfirmado: '¡Turno confirmado!',
  turnoCancelado: 'Turno cancelado',
  whatsappConfirmacion: 'Te enviamos la confirmación por WhatsApp y/o email.',
  listaEspera: 'Avisame cuando haya turno',
  listaEsperaTitulo: 'Lista de espera',
  listaEsperaDesc: 'Dejanos tus datos y te avisamos si se libera un horario.',
  listaEsperaEnviado: '¡Listo! Te avisaremos cuando haya disponibilidad.',
  comoLlegar: 'Cómo llegar',
} as const;
